export const ERROR_000001_GetBucketListItems_ParametersDoNotExist = 'ERROR_GetBucketListItems_ParametersDoNotExist';
export const ERROR_000002_UpsertBucketListItem_ParametersDoNotExist = 'ERROR_000002_UpsertBucketListItem_ParametersDoNotExist';
export const ERROR_000003_DeleteBucketListItem_ParametersDoNotExist = 'ERROR_000003_DeleteBucketListItem_ParametersDoNotExist';
export const ERROR_000004_ProcessUser_ParametersDoNotExist = 'ERROR_000004_ProcessUser_ParametersDoNotExist';
export const ERROR_000005_ProcessUserRegistration_ParametersDoNotExist = 'ERROR_000005_ProcessUserRegistration_ParametersDoNotExist';

export const ERROR_000001_AWS_GetBucketListItems_ParametersDoNotExist = 'ERROR_000001_AWS_GetBucketListItems_ParametersDoNotExist';
export const ERROR_000002_AWS_DeleteBucketListItem_ParametersDoNotExist = 'ERROR_000002_AWS_DeleteBucketListItem_ParametersDoNotExist';
export const ERROR_000003_AWS_CreateBucketListItem_ParametersDoNotExist = 'ERROR_000003_AWS_CreateBucketListItem_ParametersDoNotExist';
